[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim', 'vim-pyenv', 'vim-virtualenv']
on_ft = ['python']
on_event = 'InsertCharPre'
hook_source = '''
    let g:deoplete#sources#jedi#statement_length = 0
    let g:deoplete#sources#jedi#short_types = 0
    let g:deoplete#sources#jedi#show_docstring = 0
    let g:deoplete#sources#jedi#worker_threads = 2
    " let g:deoplete#sources#jedi#python_path = g:python3_host_prog
'''

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = ['python', 'djangohtml']

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = ['python']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_event = 'InsertCharPre'
on_ft = ['python']

[[plugins]]
repo = 'aliev/vim-compiler-python'
on_ft = ['python']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
depends = ['vim-pyenv', 'vim-virtualenv']
hook_source = '''
    " Disable auto init
    let g:jedi#auto_initialization = 1
    let g:jedi#auto_vim_configuration = 0

    " Disable auto complesions
    let g:jedi#completions_enabled = 0
    let g:jedi#popup_on_dot = 0
    let g:jedi#smart_auto_mappings = 0
    let g:jedi#show_call_signatures = 0

    " Custom keymap
    let g:jedi#goto_command = "<C-]>"
    let g:jedi#goto_assignments_command = "<Localleader>g"
    let g:jedi#goto_definitions_command = ""
    let g:jedi#documentation_command = "K"
    let g:jedi#usages_command = "<Localleader>n"
    let g:jedi#rename_command = "<Localleader>R"
'''
