[settings]
experimental = true
trusted_config_paths = [
"~/dev/src/github.com/MobilityTechnologies",
]
idiomatic_version_file_enable_tools = ["node"]

[tools]
go = "1.25.5"
"go:golang.org/x/tools/gopls" = "latest"
node = "25"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:biome" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:@github/copilot-language-server" = "latest"
python = "3.14.2"
uv = "0.9.25"
